### ISSUE TITLE
Protect master branch with required reviews and CI

### ISSUE THREAD

**Issue by relud** [mozilla/addons_daily#18]
#17 will enable CI, after which someone with admin on this repo should go to https://github.com/mozilla/bigquery-etl/settings/branch_protection_rules/new 
and configure the settings pictured below and hit "create"

<img width="744" alt="Screen Shot 2019-05-08 at 8 16 04 AM" src="https://user-images.githubusercontent.com/433717/57386615-906bcf00-7169-11e9-9c1e-9db37d69b82f.png">

**Comment by benmiroglio** [comment]
@brianwright2 @smelancon  ^

**Comment by relud** [comment]
instead of requiring **`ci/circlei: build`** it will be **`ci/circlei: py27`** and **`ci/circlei: py3`**
